# Generated by Django 4.0.4 on 2022-04-28 10:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('speed', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.datetime(2022, 5, 28, 15, 54, 22, 455104))),
                ('is_active', models.BooleanField(default=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plans')),
            ],
        ),
    ]
