# Generated by Django 4.0.4 on 2022-05-09 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 16, 7, 45, 227527)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
