# Generated by Django 4.0.4 on 2022-05-09 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_orders_end_date_alter_orders_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 6, 8, 17, 39, 12, 61666)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
